<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ReadRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'pids_supported_01_20' => 'nullable|string|max:255',
            'monitor_status_since_dtcs_cleared' => 'nullable|string|max:255',
            'freeze_dtc' => 'nullable|string|max:255',
            'fuel_system_status' => 'nullable|string|max:255',
            'calculated_engine_load' => 'nullable|string|max:255',
            'engine_coolant_temperature' => 'nullable|string|max:255',
            'short_term_fuel_trim_bank_1' => 'nullable|string|max:255',
            'long_term_fuel_trim_bank_1' => 'nullable|string|max:255',
            'short_term_fuel_trim_bank_2' => 'nullable|string|max:255',
            'long_term_fuel_trim_bank_2' => 'nullable|string|max:255',
            'fuel_pressure' => 'nullable|string|max:255',
            'intake_manifold_absolute_pressure' => 'nullable|string|max:255',
            'engine_rpm' => 'nullable|string|max:255',
            'vehicle_speed' => 'nullable|string|max:255',
            'timing_advance' => 'nullable|string|max:255',
            'intake_air_temperature' => 'nullable|string|max:255',
            'maf_air_flow_rate' => 'nullable|string|max:255',
            'throttle_position' => 'nullable|string|max:255',
            'commanded_secondary_air_status' => 'nullable|string|max:255',
            'oxygen_sensors_present_2_banks' => 'nullable|string|max:255',
            'oxygen_sensor_1_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_2_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_3_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_4_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_5_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_6_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_7_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_8_short_term_fuel_trim' => 'nullable|string|max:255',
            'obd_standards_vehicle_conforms_to' => 'nullable|string|max:255',
            'oxygen_sensors_present_4_banks' => 'nullable|string|max:255',
            'auxiliary_input_status' => 'nullable|string|max:255',
            'run_time_since_engine_start' => 'nullable|string|max:255',
            'pids_supported_21_40' => 'nullable|string|max:255',
            'distance_traveled_with_mil_on' => 'nullable|string|max:255',
            'fuel_rail_pressure_relative_to_manifold_vacuum' => 'nullable|string|max:255',
            'fuel_rail_gauge_pressure' => 'nullable|string|max:255',
            'oxygen_sensor_1_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_2_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_3_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_4_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_5_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_6_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_7_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_8_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'commanded_egr' => 'nullable|string|max:255',
            'egr_error' => 'nullable|string|max:255',
            'commanded_evaporative_purge' => 'nullable|string|max:255',
            'fuel_tank_level_input' => 'nullable|string|max:255',
            'warm_ups_since_codes_cleared' => 'nullable|string|max:255',
            'distance_traveled_since_codes_cleared' => 'nullable|string|max:255',
            'evap_system_vapor_pressure' => 'nullable|string|max:255',
            'absolute_barometric_pressure' => 'nullable|string|max:255',
            'oxygen_sensor_1_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_2_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_3_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_4_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_5_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_6_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_7_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_8_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'catalyst_temp_bank_1_sensor_1' => 'nullable|string|max:255',
            'catalyst_temp_bank_2_sensor_1' => 'nullable|string|max:255',
            'catalyst_temp_bank_1_sensor_2' => 'nullable|string|max:255',
            'catalyst_temp_bank_2_sensor_2' => 'nullable|string|max:255',
            'pids_supported_41_60' => 'nullable|string|max:255',
            'monitor_status_this_drive_cycle' => 'nullable|string|max:255',
            'control_module_voltage' => 'nullable|string|max:255',
            'absolute_load_value' => 'nullable|string|max:255',
            'fuel_air_commanded_eq_ratio' => 'nullable|string|max:255',
            'relative_throttle_position' => 'nullable|string|max:255',
            'ambient_air_temperature' => 'nullable|string|max:255',
            'absolute_throttle_position_b' => 'nullable|string|max:255',
            'absolute_throttle_position_c' => 'nullable|string|max:255',
            'absolute_throttle_position_d' => 'nullable|string|max:255',
            'absolute_throttle_position_e' => 'nullable|string|max:255',
            'absolute_throttle_position_f' => 'nullable|string|max:255',
            'commanded_throttle_actuator' => 'nullable|string|max:255',
            'time_run_with_mil_on' => 'nullable|string|max:255',
            'time_since_trouble_codes_cleared' => 'nullable|string|max:255',
            'max_value_for_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'max_value_for_air_flow_rate_from_maf' => 'nullable|string|max:255',
            'fuel_type' => 'nullable|string|max:255',
            'ethanol_fuel_percentage' => 'nullable|string|max:255',
            'absolute_evap_system_vapor_pressure' => 'nullable|string|max:255',
            'evap_system_vapor_pressure_2' => 'nullable|string|max:255',
            'short_term_secondary_oxygen_sensor_trim' => 'nullable|string|max:255',
            'long_term_secondary_oxygen_sensor_trim' => 'nullable|string|max:255',
            'short_term_secondary_oxygen_sensor_trim_2' => 'nullable|string|max:255',
            'long_term_secondary_oxygen_sensor_trim_2' => 'nullable|string|max:255',
            'fuel_rail_absolute_pressure' => 'nullable|string|max:255',
            'relative_accelerator_pedal_position' => 'nullable|string|max:255',
            'hybrid_battery_pack_remaining_life' => 'nullable|string|max:255',
            'engine_oil_temperature' => 'nullable|string|max:255',
            'fuel_injection_timing' => 'nullable|string|max:255',
            'engine_fuel_rate' => 'nullable|string|max:255',
            'emission_requirements_to_vehicle' => 'nullable|string|max:255',
        ];
    }

    public function messages() {
        return [
            'pids_supported_01_20.string' => 'O pids_supported_01_20 deve ser uma string.',
            'monitor_status_since_dtcs_cleared.string' => 'O monitor_status_since_dtcs_cleared deve ser uma string.',
            'freeze_dtc.string' => 'O freeze_dtc deve ser uma string.',
            'fuel_system_status.string' => 'O fuel_system_status deve ser uma string.',
            'calculated_engine_load.string' => 'O calculated_engine_load deve ser uma string.',
            'engine_coolant_temperature.string' => 'O engine_coolant_temperature deve ser uma string.',
            'short_term_fuel_trim_bank_1.string' => 'O short_term_fuel_trim_bank_1 deve ser uma string.',
            'long_term_fuel_trim_bank_1.string' => 'O long_term_fuel_trim_bank_1 deve ser uma string.',
            'short_term_fuel_trim_bank_2.string' => 'O short_term_fuel_trim_bank_2 deve ser uma string.',
            'long_term_fuel_trim_bank_2.string' => 'O long_term_fuel_trim_bank_2 deve ser uma string.',
            'fuel_pressure.string' => 'O fuel_pressure deve ser uma string.',
            'intake_manifold_absolute_pressure.string' => 'O intake_manifold_absolute_pressure deve ser uma string.',
            'engine_rpm.string' => 'O engine_rpm deve ser uma string.',
            'vehicle_speed.string' => 'O vehicle_speed deve ser uma string.',
            'timing_advance.string' => 'O timing_advance deve ser uma string.',
            'intake_air_temperature.string' => 'O intake_air_temperature deve ser uma string.',
            'maf_air_flow_rate.string' => 'O maf_air_flow_rate deve ser uma string.',
            'throttle_position.string' => 'O throttle_position deve ser uma string.',
            'commanded_secondary_air_status.string' => 'O commanded_secondary_air_status deve ser uma string.',
            'oxygen_sensors_present_2_banks.string' => 'O oxygen_sensors_present_2_banks deve ser uma string.',
            'oxygen_sensor_1_short_term_fuel_trim.string' => 'O oxygen_sensor_1_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_2_short_term_fuel_trim.string' => 'O oxygen_sensor_2_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_3_short_term_fuel_trim.string' => 'O oxygen_sensor_3_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_4_short_term_fuel_trim.string' => 'O oxygen_sensor_4_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_5_short_term_fuel_trim.string' => 'O oxygen_sensor_5_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_6_short_term_fuel_trim.string' => 'O oxygen_sensor_6_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_7_short_term_fuel_trim.string' => 'O oxygen_sensor_7_short_term_fuel_trim deve ser uma string.',
            'oxygen_sensor_8_short_term_fuel_trim.string' => 'O oxygen_sensor_8_short_term_fuel_trim deve ser uma string.',
            'obd_standards_vehicle_conforms_to.string' => 'O obd_standards_vehicle_conforms_to deve ser uma string.',
            'oxygen_sensors_present_4_banks.string' => 'O oxygen_sensors_present_4_banks deve ser uma string.',
            'auxiliary_input_status.string' => 'O auxiliary_input_status deve ser uma string.',
            'run_time_since_engine_start.string' => 'O run_time_since_engine_start deve ser uma string.',
            'pids_supported_21_40.string' => 'O pids_supported_21_40 deve ser uma string.',
            'distance_traveled_with_mil_on.string' => 'O distance_traveled_with_mil_on deve ser uma string.',
            'fuel_rail_pressure_relative_to_manifold_vacuum.string' => 'O fuel_rail_pressure_relative_to_manifold_vacuum deve ser uma string.',
            'fuel_rail_gauge_pressure.string' => 'O fuel_rail_gauge_pressure deve ser uma string.',
            'oxygen_sensor_1_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_1_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_2_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_2_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_3_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_3_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_4_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_4_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_5_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_5_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_6_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_6_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_7_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_7_fuel_air_equivalence_ratio deve ser uma string.',
            'oxygen_sensor_8_fuel_air_equivalence_ratio.string' => 'O oxygen_sensor_8_fuel_air_equivalence_ratio deve ser uma string.',
            'commanded_egr.string' => 'O commanded_egr deve ser uma string.',
            'egr_error.string' => 'O egr_error deve ser uma string.',
            'commanded_evaporative_purge.string' => 'O commanded_evaporative_purge deve ser uma string.',
            'fuel_tank_level_input.string' => 'O fuel_tank_level_input deve ser uma string.',
            'warm_ups_since_codes_cleared.string' => 'O warm_ups_since_codes_cleared deve ser uma string.',
            'distance_traveled_since_codes_cleared.string' => 'O distance_traveled_since_codes_cleared deve ser uma string.',
            'evap_system_vapor_pressure.string' => 'O evap_system_vapor_pressure deve ser uma string.',
            'absolute_barometric_pressure.string' => 'O absolute_barometric_pressure deve ser uma string.',
            'oxygen_sensor_1_fuel_air_eq_ratio.string' => 'O oxygen_sensor_1_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_2_fuel_air_eq_ratio.string' => 'O oxygen_sensor_2_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_3_fuel_air_eq_ratio.string' => 'O oxygen_sensor_3_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_4_fuel_air_eq_ratio.string' => 'O oxygen_sensor_4_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_5_fuel_air_eq_ratio.string' => 'O oxygen_sensor_5_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_6_fuel_air_eq_ratio.string' => 'O oxygen_sensor_6_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_7_fuel_air_eq_ratio.string' => 'O oxygen_sensor_7_fuel_air_eq_ratio deve ser uma string.',
            'oxygen_sensor_8_fuel_air_eq_ratio.string' => 'O oxygen_sensor_8_fuel_air_eq_ratio deve ser uma string.',
            'catalyst_temp_bank_1_sensor_1.string' => 'O catalyst_temp_bank_1_sensor_1 deve ser uma string.',
            'catalyst_temp_bank_2_sensor_1.string' => 'O catalyst_temp_bank_2_sensor_1 deve ser uma string.',
            'catalyst_temp_bank_1_sensor_2.string' => 'O catalyst_temp_bank_1_sensor_2 deve ser uma string.',
            'catalyst_temp_bank_2_sensor_2.string' => 'O catalyst_temp_bank_2_sensor_2 deve ser uma string.',
            'pids_supported_41_60.string' => 'Os pids_supported_41_60 devem ser uma string.',
            'monitor_status_this_drive_cycle.string' => 'O monitor_status_this_drive_cycle deve ser uma string.',
            'control_module_voltage.string' => 'A voltagem do módulo de controle deve ser uma string.',
            'absolute_load_value.string' => 'O valor de carga absoluta deve ser uma string.',
            'fuel_air_commanded_eq_ratio.string' => 'A relação ar/combustível comandada deve ser uma string.',
            'relative_throttle_position.string' => 'A posição relativa do acelerador deve ser uma string.',
            'ambient_air_temperature.string' => 'A temperatura ambiente deve ser uma string.',
            'absolute_throttle_position_b.string' => 'A posição absoluta do acelerador B deve ser uma string.',
            'absolute_throttle_position_c.string' => 'A posição absoluta do acelerador C deve ser uma string.',
            'absolute_throttle_position_d.string' => 'A posição absoluta do acelerador D deve ser uma string.',
            'absolute_throttle_position_e.string' => 'A posição absoluta do acelerador E deve ser uma string.',
            'absolute_throttle_position_f.string' => 'A posição absoluta do acelerador F deve ser uma string.',
            'commanded_throttle_actuator.string' => 'O atuador do acelerador comandado deve ser uma string.',
            'time_run_with_mil_on.string' => 'O tempo de execução com a MIL acesa deve ser uma string.',
            'time_since_trouble_codes_cleared.string' => 'O tempo desde que os códigos de problema foram apagados deve ser uma string.',
            'max_value_for_fuel_air_eq_ratio.string' => 'O valor máximo para a relação de equivalência ar/combustível deve ser uma string.',
            'max_value_for_air_flow_rate_from_maf.string' => 'O valor máximo para a taxa de fluxo de ar do MAF deve ser uma string.',
            'fuel_type.string' => 'O tipo de combustível deve ser uma string.',
            'ethanol_fuel_percentage.string' => 'A porcentagem de etanol no combustível deve ser uma string.',
            'absolute_evap_system_vapor_pressure.string' => 'A pressão absoluta do vapor do sistema EVAP deve ser uma string.',
            'evap_system_vapor_pressure_2.string' => 'A pressão de vapor do sistema EVAP 2 deve ser uma string.',
            'short_term_secondary_oxygen_sensor_trim.string' => 'O ajuste do sensor de oxigênio secundário de curto prazo deve ser uma string.',
            'long_term_secondary_oxygen_sensor_trim.string' => 'O ajuste do sensor de oxigênio secundário de longo prazo deve ser uma string.',
            'short_term_secondary_oxygen_sensor_trim_2.string' => 'O ajuste 2 do sensor de oxigênio secundário de curto prazo deve ser uma string.',
            'long_term_secondary_oxygen_sensor_trim_2.string' => 'O ajuste 2 do sensor de oxigênio secundário de longo prazo deve ser uma string.',
            'fuel_rail_absolute_pressure.string' => 'A pressão absoluta do trilho de combustível deve ser uma string.',
            'relative_accelerator_pedal_position.string' => 'A posição relativa do pedal do acelerador deve ser uma string.',
            'hybrid_battery_pack_remaining_life.string' => 'A vida restante do pacote de bateria híbrida deve ser uma string.',
            'engine_oil_temperature.string' => 'A temperatura do óleo do motor deve ser uma string.',
            'fuel_injection_timing.string' => 'O tempo de injeção de combustível deve ser uma string.',
            'engine_fuel_rate.string' => 'A taxa de combustível do motor deve ser uma string.',
            'emission_requirements_to_vehicle' => 'Os requisitos de emissão para o veículo'
        ];
    }
}
