<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ReadRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'pids_supported_01_20' => 'nullable|string|max:255',
            'monitor_status_since_dtcs_cleared' => 'nullable|string|max:255',
            'freeze_dtc' => 'nullable|string|max:255',
            'fuel_system_status' => 'nullable|string|max:255',
            'calculated_engine_load' => 'nullable|string|max:255',
            'engine_coolant_temperature' => 'nullable|string|max:255',
            'short_term_fuel_trim_bank_1' => 'nullable|string|max:255',
            'long_term_fuel_trim_bank_1' => 'nullable|string|max:255',
            'short_term_fuel_trim_bank_2' => 'nullable|string|max:255',
            'long_term_fuel_trim_bank_2' => 'nullable|string|max:255',
            'fuel_pressure' => 'nullable|string|max:255',
            'intake_manifold_absolute_pressure' => 'nullable|string|max:255',
            'engine_rpm' => 'nullable|string|max:255',
            'vehicle_speed' => 'nullable|string|max:255',
            'timing_advance' => 'nullable|string|max:255',
            'intake_air_temperature' => 'nullable|string|max:255',
            'maf_air_flow_rate' => 'nullable|string|max:255',
            'throttle_position' => 'nullable|string|max:255',
            'commanded_secondary_air_status' => 'nullable|string|max:255',
            'oxygen_sensors_present_2_banks' => 'nullable|string|max:255',
            'oxygen_sensor_1_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_2_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_3_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_4_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_5_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_6_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_7_short_term_fuel_trim' => 'nullable|string|max:255',
            'oxygen_sensor_8_short_term_fuel_trim' => 'nullable|string|max:255',
            'obd_standards_vehicle_conforms_to' => 'nullable|string|max:255',
            'oxygen_sensors_present_4_banks' => 'nullable|string|max:255',
            'auxiliary_input_status' => 'nullable|string|max:255',
            'run_time_since_engine_start' => 'nullable|string|max:255',
            'pids_supported_21_40' => 'nullable|string|max:255',
            'distance_traveled_with_mil_on' => 'nullable|string|max:255',
            'fuel_rail_pressure_relative_to_manifold_vacuum' => 'nullable|string|max:255',
            'fuel_rail_gauge_pressure' => 'nullable|string|max:255',
            'oxygen_sensor_1_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_2_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_3_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_4_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_5_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_6_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_7_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_8_fuel_air_equivalence_ratio' => 'nullable|string|max:255',
            'commanded_egr' => 'nullable|string|max:255',
            'egr_error' => 'nullable|string|max:255',
            'commanded_evaporative_purge' => 'nullable|string|max:255',
            'fuel_tank_level_input' => 'nullable|string|max:255',
            'warm_ups_since_codes_cleared' => 'nullable|string|max:255',
            'distance_traveled_since_codes_cleared' => 'nullable|string|max:255',
            'evap_system_vapor_pressure' => 'nullable|string|max:255',
            'absolute_barometric_pressure' => 'nullable|string|max:255',
            'oxygen_sensor_1_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_2_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_3_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_4_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_5_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_6_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_7_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'oxygen_sensor_8_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'catalyst_temp_bank_1_sensor_1' => 'nullable|string|max:255',
            'catalyst_temp_bank_2_sensor_1' => 'nullable|string|max:255',
            'catalyst_temp_bank_1_sensor_2' => 'nullable|string|max:255',
            'catalyst_temp_bank_2_sensor_2' => 'nullable|string|max:255',
            'pids_supported_41_60' => 'nullable|string|max:255',
            'monitor_status_this_drive_cycle' => 'nullable|string|max:255',
            'control_module_voltage' => 'nullable|string|max:255',
            'absolute_load_value' => 'nullable|string|max:255',
            'fuel_air_commanded_eq_ratio' => 'nullable|string|max:255',
            'relative_throttle_position' => 'nullable|string|max:255',
            'ambient_air_temperature' => 'nullable|string|max:255',
            'absolute_throttle_position_b' => 'nullable|string|max:255',
            'absolute_throttle_position_c' => 'nullable|string|max:255',
            'absolute_throttle_position_d' => 'nullable|string|max:255',
            'absolute_throttle_position_e' => 'nullable|string|max:255',
            'absolute_throttle_position_f' => 'nullable|string|max:255',
            'commanded_throttle_actuator' => 'nullable|string|max:255',
            'time_run_with_mil_on' => 'nullable|string|max:255',
            'time_since_trouble_codes_cleared' => 'nullable|string|max:255',
            'max_value_for_fuel_air_eq_ratio' => 'nullable|string|max:255',
            'max_value_for_air_flow_rate_from_maf' => 'nullable|string|max:255',
            'fuel_type' => 'nullable|string|max:255',
            'ethanol_fuel_percentage' => 'nullable|string|max:255',
            'absolute_evap_system_vapor_pressure' => 'nullable|string|max:255',
            'evap_system_vapor_pressure_2' => 'nullable|string|max:255',
            'short_term_secondary_oxygen_sensor_trim' => 'nullable|string|max:255',
            'long_term_secondary_oxygen_sensor_trim' => 'nullable|string|max:255',
            'short_term_secondary_oxygen_sensor_trim_2' => 'nullable|string|max:255',
            'long_term_secondary_oxygen_sensor_trim_2' => 'nullable|string|max:255',
            'fuel_rail_absolute_pressure' => 'nullable|string|max:255',
            'relative_accelerator_pedal_position' => 'nullable|string|max:255',
            'hybrid_battery_pack_remaining_life' => 'nullable|string|max:255',
            'engine_oil_temperature' => 'nullable|string|max:255',
            'fuel_injection_timing' => 'nullable|string|max:255',
            'engine_fuel_rate' => 'nullable|string|max:255',
            'emission_requirements_to_vehicle' => 'nullable|string|max:255',
        ];
    }

    public function messages() {
        return [
            'pids_supported_01_20.string' => 'The pids_supported_01_20 must be a string.',
            'monitor_status_since_dtcs_cleared.string' => 'The monitor_status_since_dtcs_cleared must be a string.',
            'freeze_dtc.string' => 'The freeze_dtc must be a string.',
            'fuel_system_status.string' => 'The fuel_system_status must be a string.',
            'calculated_engine_load.string' => 'The calculated_engine_load must be a string.',
            'engine_coolant_temperature.string' => 'The engine_coolant_temperature must be a string.',
            'short_term_fuel_trim_bank_1.string' => 'The short_term_fuel_trim_bank_1 must be a string.',
            'long_term_fuel_trim_bank_1.string' => 'The long_term_fuel_trim_bank_1 must be a string.',
            'short_term_fuel_trim_bank_2.string' => 'The short_term_fuel_trim_bank_2 must be a string.',
            'long_term_fuel_trim_bank_2.string' => 'The long_term_fuel_trim_bank_2 must be a string.',
            'fuel_pressure.string' => 'The fuel_pressure must be a string.',
            'intake_manifold_absolute_pressure.string' => 'The intake_manifold_absolute_pressure must be a string.',
            'engine_rpm.string' => 'The engine_rpm must be a string.',
            'vehicle_speed.string' => 'The vehicle_speed must be a string.',
            'timing_advance.string' => 'The timing_advance must be a string.',
            'intake_air_temperature.string' => 'The intake_air_temperature must be a string.',
            'maf_air_flow_rate.string' => 'The maf_air_flow_rate must be a string.',
            'throttle_position.string' => 'The throttle_position must be a string.',
            'commanded_secondary_air_status.string' => 'The commanded_secondary_air_status must be a string.',
            'oxygen_sensors_present_2_banks.string' => 'The oxygen_sensors_present_2_banks must be a string.',
            'oxygen_sensor_1_short_term_fuel_trim.string' => 'The oxygen_sensor_1_short_term_fuel_trim must be a string.',
            'oxygen_sensor_2_short_term_fuel_trim.string' => 'The oxygen_sensor_2_short_term_fuel_trim must be a string.',
            'oxygen_sensor_3_short_term_fuel_trim.string' => 'The oxygen_sensor_3_short_term_fuel_trim must be a string.',
            'oxygen_sensor_4_short_term_fuel_trim.string' => 'The oxygen_sensor_4_short_term_fuel_trim must be a string.',
            'oxygen_sensor_5_short_term_fuel_trim.string' => 'The oxygen_sensor_5_short_term_fuel_trim must be a string.',
            'oxygen_sensor_6_short_term_fuel_trim.string' => 'The oxygen_sensor_6_short_term_fuel_trim must be a string.',
            'oxygen_sensor_7_short_term_fuel_trim.string' => 'The oxygen_sensor_7_short_term_fuel_trim must be a string.',
            'oxygen_sensor_8_short_term_fuel_trim.string' => 'The oxygen_sensor_8_short_term_fuel_trim must be a string.',
            'obd_standards_vehicle_conforms_to.string' => 'The obd_standards_vehicle_conforms_to must be a string.',
            'oxygen_sensors_present_4_banks.string' => 'The oxygen_sensors_present_4_banks must be a string.',
            'auxiliary_input_status.string' => 'The auxiliary_input_status must be a string.',
            'run_time_since_engine_start.string' => 'The run_time_since_engine_start must be a string.',
            'pids_supported_21_40.string' => 'The pids_supported_21_40 must be a string.',
            'distance_traveled_with_mil_on.string' => 'The distance_traveled_with_mil_on must be a string.',
            'fuel_rail_pressure_relative_to_manifold_vacuum.string' => 'The fuel_rail_pressure_relative_to_manifold_vacuum must be a string.',
            'fuel_rail_gauge_pressure.string' => 'The fuel_rail_gauge_pressure must be a string.',
            'oxygen_sensor_1_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_1_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_2_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_2_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_3_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_3_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_4_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_4_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_5_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_5_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_6_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_6_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_7_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_7_fuel_air_equivalence_ratio must be a string.',
            'oxygen_sensor_8_fuel_air_equivalence_ratio.string' => 'The oxygen_sensor_8_fuel_air_equivalence_ratio must be a string.',
            'commanded_egr.string' => 'The commanded_egr must be a string.',
            'egr_error.string' => 'The egr_error must be a string.',
            'commanded_evaporative_purge.string' => 'The commanded_evaporative_purge must be a string.',
            'fuel_tank_level_input.string' => 'The fuel_tank_level_input must be a string.',
            'warm_ups_since_codes_cleared.string' => 'The warm_ups_since_codes_cleared must be a string.',
            'distance_traveled_since_codes_cleared.string' => 'The distance_traveled_since_codes_cleared must be a string.',
            'evap_system_vapor_pressure.string' => 'The evap_system_vapor_pressure must be a string.',
            'absolute_barometric_pressure.string' => 'The absolute_barometric_pressure must be a string.',
            'oxygen_sensor_1_fuel_air_eq_ratio.string' => 'The oxygen_sensor_1_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_2_fuel_air_eq_ratio.string' => 'The oxygen_sensor_2_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_3_fuel_air_eq_ratio.string' => 'The oxygen_sensor_3_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_4_fuel_air_eq_ratio.string' => 'The oxygen_sensor_4_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_5_fuel_air_eq_ratio.string' => 'The oxygen_sensor_5_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_6_fuel_air_eq_ratio.string' => 'The oxygen_sensor_6_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_7_fuel_air_eq_ratio.string' => 'The oxygen_sensor_7_fuel_air_eq_ratio must be a string.',
            'oxygen_sensor_8_fuel_air_eq_ratio.string' => 'The oxygen_sensor_8_fuel_air_eq_ratio must be a string.',
            'catalyst_temp_bank_1_sensor_1.string' => 'The catalyst_temp_bank_1_sensor_1 must be a string.',
            'catalyst_temp_bank_2_sensor_1.string' => 'The catalyst_temp_bank_2_sensor_1 must be a string.',
            'catalyst_temp_bank_1_sensor_2.string' => 'The catalyst_temp_bank_1_sensor_2 must be a string.',
            'catalyst_temp_bank_2_sensor_2.string' => 'The catalyst_temp_bank_2_sensor_2 must be a string.',
            'pids_supported_41_60.string' => 'The pids_supported_41_60 must be a string.',
            'monitor_status_this_drive_cycle.string' => 'The monitor_status_this_drive_cycle must be a string.',
            'control_module_voltage.string' => 'The control_module_voltage must be a string.',
            'absolute_load_value.string' => 'The absolute_load_value must be a string.',
            'fuel_air_commanded_eq_ratio.string' => 'The fuel_air_commanded_eq_ratio must be a string.',
            'relative_throttle_position.string' => 'The relative_throttle_position must be a string.',
            'ambient_air_temperature.string' => 'The ambient_air_temperature must be a string.',
            'absolute_throttle_position_b.string' => 'The absolute_throttle_position_b must be a string.',
            'absolute_throttle_position_c.string' => 'The absolute_throttle_position_c must be a string.',
            'absolute_throttle_position_d.string' => 'The absolute_throttle_position_d must be a string.',
            'absolute_throttle_position_e.string' => 'The absolute_throttle_position_e must be a string.',
            'absolute_throttle_position_f.string' => 'The absolute_throttle_position_f must be a string.',
            'commanded_throttle_actuator.string' => 'The commanded_throttle_actuator must be a string.',
            'time_run_with_mil_on.string' => 'The time_run_with_mil_on must be a string.',
            'time_since_trouble_codes_cleared.string' => 'The time_since_trouble_codes_cleared must be a string.',
            'max_value_for_fuel_air_eq_ratio.string' => 'The max_value_for_fuel_air_eq_ratio must be a string.',
            'max_value_for_air_flow_rate_from_maf.string' => 'The max_value_for_air_flow_rate_from_maf must be a string.',
            'fuel_type.string' => 'The fuel_type must be a string.',
            'ethanol_fuel_percentage.string' => 'The ethanol_fuel_percentage must be a string.',
            'absolute_evap_system_vapor_pressure.string' => 'The absolute_evap_system_vapor_pressure must be a string.',
            'evap_system_vapor_pressure_2.string' => 'The evap_system_vapor_pressure_2 must be a string.',
            'short_term_secondary_oxygen_sensor_trim.string' => 'The short_term_secondary_oxygen_sensor_trim must be a string.',
            'long_term_secondary_oxygen_sensor_trim.string' => 'The long_term_secondary_oxygen_sensor_trim must be a string.',
            'short_term_secondary_oxygen_sensor_trim_2.string' => 'The short_term_secondary_oxygen_sensor_trim_2 must be a string.',
            'long_term_secondary_oxygen_sensor_trim_2.string' => 'The long_term_secondary_oxygen_sensor_trim_2 must be a string.',
            'fuel_rail_absolute_pressure.string' => 'The fuel_rail_absolute_pressure must be a string.',
            'relative_accelerator_pedal_position.string' => 'The relative_accelerator_pedal_position must be a string.',
            'hybrid_battery_pack_remaining_life.string' => 'The hybrid_battery_pack_remaining_life must be a string.',
            'engine_oil_temperature.string' => 'The engine_oil_temperature must be a string.',
            'fuel_injection_timing.string' => 'The fuel_injection_timing must be a string.',
            'engine_fuel_rate.string' => 'The engine_fuel_rate must be a string.',
            'emission_requirements_to_vehicle'
        ];
    }
}
