<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Read extends Model
{
    use HasFactory;

    protected $fillable = [
        'pids_supported_01_20',
        'monitor_status_since_dtcs_cleared',
        'freeze_dtc',
        'fuel_system_status',
        'calculated_engine_load',
        'engine_coolant_temperature',
        'short_term_fuel_trim_bank_1',
        'long_term_fuel_trim_bank_1',
        'short_term_fuel_trim_bank_2',
        'long_term_fuel_trim_bank_2',
        'fuel_pressure',
        'intake_manifold_absolute_pressure',
        'engine_rpm',
        'vehicle_speed',
        'timing_advance',
        'intake_air_temperature',
        'maf_air_flow_rate',
        'throttle_position',
        'commanded_secondary_air_status',
        'oxygen_sensors_present_2_banks',
        'oxygen_sensor_1_short_term_fuel_trim',
        'oxygen_sensor_2_short_term_fuel_trim',
        'oxygen_sensor_3_short_term_fuel_trim',
        'oxygen_sensor_4_short_term_fuel_trim',
        'oxygen_sensor_5_short_term_fuel_trim',
        'oxygen_sensor_6_short_term_fuel_trim',
        'oxygen_sensor_7_short_term_fuel_trim',
        'oxygen_sensor_8_short_term_fuel_trim',
        'obd_standards_vehicle_conforms_to',
        'oxygen_sensors_present_4_banks',
        'auxiliary_input_status',
        'run_time_since_engine_start',
        'pids_supported_21_40',
        'distance_traveled_with_mil_on',
        'fuel_rail_pressure_relative_to_manifold_vacuum',
        'fuel_rail_gauge_pressure',
        'oxygen_sensor_1_fuel_air_equivalence_ratio',
        'oxygen_sensor_2_fuel_air_equivalence_ratio',
        'oxygen_sensor_3_fuel_air_equivalence_ratio',
        'oxygen_sensor_4_fuel_air_equivalence_ratio',
        'oxygen_sensor_5_fuel_air_equivalence_ratio',
        'oxygen_sensor_6_fuel_air_equivalence_ratio',
        'oxygen_sensor_7_fuel_air_equivalence_ratio',
        'oxygen_sensor_8_fuel_air_equivalence_ratio',
        'commanded_egr',
        'egr_error',
        'commanded_evaporative_purge',
        'fuel_tank_level_input',
        'warm_ups_since_codes_cleared',
        'distance_traveled_since_codes_cleared',
        'evap_system_vapor_pressure',
        'absolute_barometric_pressure',
        'oxygen_sensor_1_fuel_air_eq_ratio',
        'oxygen_sensor_2_fuel_air_eq_ratio',
        'oxygen_sensor_3_fuel_air_eq_ratio',
        'oxygen_sensor_4_fuel_air_eq_ratio',
        'oxygen_sensor_5_fuel_air_eq_ratio',
        'oxygen_sensor_6_fuel_air_eq_ratio',
        'oxygen_sensor_7_fuel_air_eq_ratio',
        'oxygen_sensor_8_fuel_air_eq_ratio',
        'catalyst_temp_bank_1_sensor_1',
        'catalyst_temp_bank_2_sensor_1',
        'catalyst_temp_bank_1_sensor_2',
        'catalyst_temp_bank_2_sensor_2',
        'pids_supported_41_60',
        'monitor_status_this_drive_cycle',
        'control_module_voltage',
        'absolute_load_value',
        'fuel_air_commanded_eq_ratio',
        'relative_throttle_position',
        'ambient_air_temperature',
        'absolute_throttle_position_b',
        'absolute_throttle_position_c',
        'absolute_throttle_position_d',
        'absolute_throttle_position_e',
        'absolute_throttle_position_f',
        'commanded_throttle_actuator',
        'time_run_with_mil_on',
        'time_since_trouble_codes_cleared',
        'max_value_for_fuel_air_eq_ratio',
        'max_value_for_air_flow_rate_from_maf',
        'fuel_type',
        'ethanol_fuel_percentage',
        'absolute_evap_system_vapor_pressure',
        'evap_system_vapor_pressure_2',
        'short_term_secondary_oxygen_sensor_trim',
        'long_term_secondary_oxygen_sensor_trim',
        'short_term_secondary_oxygen_sensor_trim_2',
        'long_term_secondary_oxygen_sensor_trim_2',
        'fuel_rail_absolute_pressure',
        'relative_accelerator_pedal_position',
        'hybrid_battery_pack_remaining_life',
        'engine_oil_temperature',
        'fuel_injection_timing',
        'engine_fuel_rate',
        'emission_requirements_to_vehicle'
    ];

    public function vehicle() {
        return $this->belongsTo(Vehicle::class);
    }
}
